apiVersion: v1
kind: ConfigMap
metadata:
  name: plaiss-api-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  PGBOUNCER_DB_HOST: "pg-plaiss-uk.postgres.database.azure.com"
  PGBOUNCER_DB_NAME: "plaiss"
  PGBOUNCER_DB_USER: "plaissadmin"
