apiVersion: v1
kind: ConfigMap
metadata:
  name: plaiss-api-config
data:
  NODE_ENV: "production"
  PORT: "3001"
  PGBOUNCER_DB_HOST: "eraofmarketing-db.cluster-cfu6wo4i8gx2.eu-north-1.rds.amazonaws.com"
  PGBOUNCER_DB_NAME: "eraofmarketing"
  PGBOUNCER_DB_USER: "eraadmin"
