apiVersion: v1
kind: Secret
metadata:
  name: plaiss-api-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://eraadmin:EraOfMktg2026Secure@127.0.0.1:5432/eraofmarketing?schema=public"
  POSTGRESQL_PASSWORD: "EraOfMktg2026Secure"
