apiVersion: v1
kind: Secret
metadata:
  name: plaiss-api-secrets
type: Opaque
stringData:
  DATABASE_URL: "postgresql://eraadmin:EraOfMktg2026Secure@eraofmarketing-db.cluster-cfu6wo4i8gx2.eu-north-1.rds.amazonaws.com:5432/eraofmarketing?schema=public"
